# Generated by Django 5.2.18 on 2026-10-06 18:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre o razón social')),
                ('document_type', models.CharField(choices=[('RUC', 'RUC'), ('DNI', 'DNI'), ('OTRO', 'Otro documento')], default='RUC', max_length=4, verbose_name='Tipo de documento')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('object_type', models.CharField(max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('CREDITO', 'Nota de crédito'), ('DEBITO', 'Nota de débito')], max_length=10, verbose_name='Tipo')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_document', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADO', 'Venta interna registrada')], default='BORRADOR', max_length=12)),
                ('sunat_status', models.CharField(default='NO_ENVIADO', editable=False, max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('paid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='Observaciones / motivo de la nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.customer', verbose_name='Cliente')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.document', verbose_name='Venta relacionada')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REMITENTE', 'Remisión remitente'), ('TRANSPORTISTA', 'Remisión transportista')], max_length=15, verbose_name='Tipo de guía')),
                ('transfer_date', models.DateField(verbose_name='Inicio del traslado')),
                ('reason', models.CharField(max_length=100, verbose_name='Motivo del traslado')),
                ('origin', models.CharField(max_length=250, verbose_name='Dirección de partida')),
                ('origin_ubigeo', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Ingresa un ubigeo de 6 dígitos.')], verbose_name='Ubigeo de partida')),
                ('destination', models.CharField(max_length=250, verbose_name='Dirección de llegada')),
                ('destination_ubigeo', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Ingresa un ubigeo de 6 dígitos.')], verbose_name='Ubigeo de llegada')),
                ('transport_mode', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], max_length=7, verbose_name='Modalidad')),
                ('carrier_ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC del transportista')),
                ('carrier_name', models.CharField(blank=True, max_length=200, verbose_name='Razón social del transportista')),
                ('plate', models.CharField(blank=True, max_length=15, verbose_name='Placa del vehículo')),
                ('driver_document', models.CharField(blank=True, max_length=20, verbose_name='Documento del conductor')),
                ('driver_license', models.CharField(blank=True, max_length=25, verbose_name='Licencia del conductor')),
                ('related_gre', models.CharField(blank=True, max_length=30, verbose_name='GRE remitente relacionada (serie-número)')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso bruto total (kg)')),
                ('goods', models.TextField(max_length=3000, verbose_name='Bienes a trasladar: código, descripción, cantidad y unidad')),
                ('status', models.CharField(default='BORRADOR', editable=False, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='Destinatario')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.document', verbose_name='Venta interna relacionada')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe (S/)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape / Plin'), ('TARJETA', 'Tarjeta')], max_length=15, verbose_name='Medio de pago')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia / número de operación')),
                ('request_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.document')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Producto')),
                ('unit', models.CharField(choices=[('NIU', 'Unidad'), ('KGM', 'Kilogramo'), ('MTR', 'Metro'), ('LTR', 'Litro')], default='NIU', max_length=3, verbose_name='Unidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de venta con impuesto (S/)')),
                ('tax_rate', models.DecimalField(choices=[(Decimal('18'), '18%'), (Decimal('0'), '0% — pendiente de clasificar tributariamente')], decimal_places=2, default=18, max_digits=5, verbose_name='IGV (%)')),
                ('stock', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=16)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='stock_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=16)),
                ('reason', models.CharField(max_length=250)),
                ('request_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('paid__gte', 0), ('paid__lte', models.F('total'))), name='document_paid_range'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_nonzero'),
        ),
    ]
