# Generated by Django 5.2.18 on 2026-10-06 18:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón social')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección fiscal')),
                ('ubigeo', models.CharField(blank=True, max_length=6, verbose_name='Ubigeo')),
                ('regime', models.CharField(blank=True, choices=[('RER', 'Régimen especial'), ('MYPE', 'Régimen MYPE tributario'), ('GENERAL', 'Régimen general'), ('RUS', 'Nuevo RUS')], max_length=30, verbose_name='Régimen tributario')),
                ('ose_required', models.BooleanField(default=False, verbose_name='Obligado a usar OSE')),
            ],
        ),
        migrations.CreateModel(
            name='GuideLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe a devolver (S/)')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape / Plin'), ('TARJETA', 'Tarjeta')], max_length=15, verbose_name='Medio de devolución')),
                ('reference', models.CharField(max_length=200, verbose_name='Número de operación / motivo')),
                ('request_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='document_paid_range',
        ),
        migrations.AddField(
            model_name='document',
            name='credited',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='document',
            name='debited',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='document',
            name='note_code',
            field=models.CharField(blank=True, choices=[('01', 'Anulación / interés por mora (según tipo)'), ('02', 'Aumento de valor (débito)'), ('05', 'Descuento por ítem (crédito)'), ('07', 'Devolución por ítem (crédito)')], max_length=2, verbose_name='Motivo de la nota'),
        ),
        migrations.AddField(
            model_name='document',
            name='refunded',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='document',
            name='return_stock',
            field=models.BooleanField(default=False, verbose_name='La mercadería se recibió físicamente de vuelta'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='sku',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='documentline',
            name='source_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.documentline', verbose_name='Línea de la venta original'),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Disponible para nuevas ventas'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_sku',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_unit',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='detail',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('REGISTRADO', 'Operación interna registrada'), ('CANCELADO', 'Borrador cancelado')], default='BORRADOR', max_length=12),
        ),
        migrations.AlterField(
            model_name='guide',
            name='goods',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Observaciones de bienes (registros anteriores)'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('paid__gte', 0), ('credited__gte', 0), ('debited__gte', 0), ('refunded__gte', 0), ('refunded__lte', models.F('paid'))), name='document_amounts_nonnegative'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.guide'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.document'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_positive'),
        ),
    ]
