# Generated by Django 5.2.18 on 2026-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_history_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='customer_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='document',
            name='customer_document_type',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='documentline',
            name='package_use',
            field=models.CharField(choices=[('ALIMENTO', 'Envase para alimentos a granel / inocuidad'), ('NO_APLICA', 'Otro producto: no es bolsa para llevar compras'), ('TRANSPORTE', 'Bolsa para cargar o llevar compras'), ('PENDIENTE', 'Pendiente de clasificar')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='documentline',
            name='tax_category',
            field=models.CharField(choices=[('10', 'Gravado — IGV 18%'), ('20', 'Exonerado — IGV 0%'), ('30', 'Inafecto — IGV 0%'), ('PENDIENTE', 'Pendiente de clasificación')], default='PENDIENTE', max_length=9),
        ),
        migrations.AddField(
            model_name='product',
            name='package_use',
            field=models.CharField(choices=[('ALIMENTO', 'Envase para alimentos a granel / inocuidad'), ('NO_APLICA', 'Otro producto: no es bolsa para llevar compras'), ('TRANSPORTE', 'Bolsa para cargar o llevar compras'), ('PENDIENTE', 'Pendiente de clasificar')], default='PENDIENTE', help_text='Clasifica el uso real. Envase alimenticio no implica IGV 0%. Las bolsas para llevar compras requieren tratamiento ICBPER, aún pendiente.', max_length=10, verbose_name='Uso del producto / bolsa'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_category',
            field=models.CharField(choices=[('10', 'Gravado — IGV 18%'), ('20', 'Exonerado — IGV 0%'), ('30', 'Inafecto — IGV 0%'), ('PENDIENTE', 'Pendiente de clasificación')], default='10', max_length=9, verbose_name='Afectación al IGV'),
        ),
    ]
