# Generated by Django 5.2.18 on 2026-10-07 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tax_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11)),
                ('filename', models.CharField(max_length=70)),
                ('signed_xml', models.BinaryField()),
                ('payload_zip', models.BinaryField()),
                ('sha256', models.CharField(max_length=64)),
                ('demo_certificate', models.BooleanField(default=True)),
                ('certificate_fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('PREPARADO', 'Firmado para pruebas'), ('ENVIANDO', 'Enviando a beta'), ('ACEPTADO', 'Aceptado en beta'), ('RECHAZADO', 'Rechazado en beta'), ('ERROR', 'Error de servicio'), ('INCIERTO', 'Respuesta pendiente de comprobar')], default='PREPARADO', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_code', models.CharField(blank=True, max_length=30)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('cdr_zip', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='beta_submission', to='core.document')),
            ],
        ),
    ]
