from django.urls import path
from . import views
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('clientes/', views.customers, name='customers'),
    path('clientes/nuevo/', views.customer_create, name='customer_create'),
    path('clientes/<int:pk>/cuenta/', views.account, name='account'),
    path('inventario/', views.products, name='products'),
    path('inventario/producto/', views.product_create, name='product_create'),
    path('inventario/<int:pk>/editar/', views.product_edit, name='product_edit'),
    path('inventario/movimiento/', views.stock_create, name='stock_create'),
    path('comprobantes/', views.documents, name='documents'),
    path('comprobantes/nuevo/', views.document_create, name='document_create'),
    path('comprobantes/<int:pk>/', views.document_detail, name='document_detail'),
    path('comprobantes/<int:pk>/registrar/', views.document_register, name='document_register'),
    path('comprobantes/<int:pk>/pago/', views.payment_create, name='payment_create'),
    path('comprobantes/<int:pk>/devolucion/', views.refund_create, name='refund_create'),
    path('comprobantes/<int:pk>/cancelar/', views.document_cancel, name='document_cancel'),
    path('comprobantes/<int:pk>/imprimir/', views.document_print, name='document_print'),
    path('comprobantes/<int:pk>/xml-prueba/', views.document_xml_preview, name='document_xml_preview'),
    path('comprobantes/<int:pk>/beta/preparar/', views.beta_prepare, name='beta_prepare'),
    path('comprobantes/<int:pk>/beta/', views.beta_detail, name='beta_detail'),
    path('comprobantes/<int:pk>/beta/enviar/', views.beta_send, name='beta_send'),
    path('comprobantes/<int:pk>/beta/interrumpido/', views.beta_recover, name='beta_recover'),
    path('comprobantes/<int:pk>/beta/archivo/<str:artifact>/', views.beta_download, name='beta_download'),
    path('guias/', views.guides, name='guides'),
    path('guias/nueva/', views.guide_create, name='guide_create'),
    path('guias/<int:pk>/', views.guide_detail, name='guide_detail'),
    path('guias/<int:pk>/imprimir/', views.guide_print, name='guide_print'),
    path('configuracion/', views.settings_page, name='settings'),
    path('configuracion/empresa/', views.company_edit, name='company_edit'),
    path('configuracion/administradores/', views.administrators, name='administrators'),
    path('configuracion/administradores/nuevo/', views.administrator_create, name='administrator_create'),
    path('configuracion/administradores/<int:pk>/acceso/', views.administrator_toggle, name='administrator_toggle'),
]
